<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>16b2bca7-b224-4a06-973a-078edfe55dd2</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CitadelIQ.Application\CitadelIQ.Application.csproj" />
    <ProjectReference Include="..\CitadelIQ.Infrastructure\CitadelIQ.Infrastructure.csproj" />
    <ProjectReference Include="..\CitadelIQ.FluentMigrations\CitadelIQ.FluentMigrations.csproj" />
  </ItemGroup>

</Project>
